### ISSUE TITLE
textureview

### ISSUE THREAD

**Issue by cjclear** [tarek360/Instacapture#11]
for (int i = 0; i < viewRoots.length; i++) {
            View view = (View) getFieldValue(FIELD_NAME_VIEW, viewRoots[i]);
            if(view.getContext() instanceof LiveActivity2){
                //I have a textureview in LiveActivity2
                //if i don't add this line,it will capture my mainactivity and the textureview will be invisiable in some case
                rootViews.add(new RootViewInfo(view, params[i]));
            }
 }

**Comment by tarek360** [comment]
Could you provide me with a link of the line of code wich you mean?
