### ISSUE TITLE
Did you try on jellybean? 4.1.1

### ISSUE THREAD

**Issue by moltak** [tarek360/Instacapture#12]
Hi. I'm testing InstaCapture on several versions of android. I tested on sdk version 16, 17, 18, 24. Only on 16 an InstaCapture is failed. See the below logs. This is so strange. I checked several files on AOSP. Because the log said NoSuchFieldException  for mWindowManager. But your code is correct and fit on AOSP code. Can you check this log? Thanks.

12-20 15:06:02.988: E/InstaCapture(3330): Screenshot capture failed
12-20 15:06:02.988: E/InstaCapture(3330): Logging caught exception
12-20 15:06:02.988: E/InstaCapture(3330): com.tarek360.instacapture.exception.ScreenCapturingFailedException: java.lang.NoSuchFieldException: mWindowManager
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.FieldHelper.getFieldValue(FieldHelper.java:67)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.FieldHelper.getRootViews(FieldHelper.java:33)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.ScreenshotTaker.getScreenshotBitmap(ScreenshotTaker.java:49)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.ViewsBitmapObservable$1.call(ViewsBitmapObservable.java:27)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.ViewsBitmapObservable$1.call(ViewsBitmapObservable.java:24)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.Observable.subscribe(Observable.java:10246)
12-20 15:06:02.988: E/InstaCapture(3330): 	at rx.Observable.subscribe(Observable.java:10213)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.InstaCapture.capture(InstaCapture.java:96)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.sample.BaseSampleActivity.captureScreenshot(BaseSampleActivity.java:47)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.sample.CustomViewSampleActivity.onClickFAB(CustomViewSampleActivity.java:29)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.sample.CustomViewSampleActivity_ViewBinding$1.doClick(CustomViewSampleActivity_ViewBinding.java:33)
12-20 15:06:02.988: E/InstaCapture(3330): 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.view.View.performClick(View.java:4084)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.view.View$PerformClick.run(View.java:16966)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.os.Handler.handleCallback(Handler.java:615)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.os.Handler.dispatchMessage(Handler.java:92)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.os.Looper.loop(Looper.java:137)
12-20 15:06:02.988: E/InstaCapture(3330): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
12-20 15:06:02.988: E/InstaCapture(3330): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-20 15:06:02.988: E/InstaCapture(3330): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12-20 15:06:02.988: E/InstaCapture(3330): 	at dalvik.system.NativeStart.main(Native Method)
12-20 15:06:02.988: E/InstaCapture(3330): Caused by: java.lang.NoSuchFieldException: sWindowManager
12-20 15:06:02.988: E/InstaCapture(3330): 	at java.lang.Class.getDeclaredField(Class.java:631)
12-20 15:06:02.988: E/InstaCapture(3330): 	at com.tarek360.instacapture.screenshot.FieldHelper.getFieldValue(FieldHelper.java:63)
12-20 15:06:02.988: E/InstaCapture(3330): 	... 26 more

**Comment by tarek360** [comment]
On API 16 you get `NoSuchFieldException` all the time?
