### ISSUE TITLE
Query - Can InstaCapture capture Android Camera Feed

### ISSUE THREAD

**Issue by felixvolz** [tarek360/Instacapture#13]
I have an App that uses both a GLSurfaceView overlaid over a SurfaceView that contains the feed from the Android devices camera

If I use the Android built in Screen Capture - I get a screenshot with the UI (from my GLSurfaceView) and the Camera Feed (see attached file)

I I use InstaCapture I get a screenshot with the UI (from my GLSurfaceView) BUT NO camera feed (only a black background - see attached file)

I also attached an image of the Activity layout showing it has two child views (GLSurfaceView20 and CameraSurface)

![screenshot-21-12-2016_16-45-47 456](https://cloud.githubusercontent.com/assets/6946906/21379162/e231da76-c79f-11e6-846b-a6ac50be3f6a.jpg)
![capture](https://cloud.githubusercontent.com/assets/6946906/21379163/e2350c1e-c79f-11e6-9dc1-2758337f0c90.JPG)
![screenshot_2016-12-21-16-57-50](https://cloud.githubusercontent.com/assets/6946906/21379164/e237d728-c79f-11e6-99c8-be343d210792.png)

**Comment by felixvolz** [comment]
Am closing : this link answers my query

http://stackoverflow.com/questions/27817577/android-take-screenshot-of-surface-view-shows-black-screen

**Comment by tarek360** [comment]
thanks
