### ISSUE TITLE
cant handle activity with surfaceview

### ISSUE THREAD

**Issue by drogbababa** [tarek360/Instacapture#18]

**Comment by tarek360** [comment]
Hi,
Thank you for reporting this issue, InstaCapture support `GLSurfaceView` not `SurfaceView` and you can test it [here](https://github.com/tarek360/InstaCapture/blob/develop/app/src/main/java/com/tarek360/sample/GLSurfaceViewSampleActivity.java) if you have an issue with `GLSurfaceView` please provide a code sample.

**Comment by crossle** [comment]
How to capture SurfaceView?
