### ISSUE TITLE
Setting android:allowBackup="false" on AndroidManifest.xml shows below error.

### ISSUE THREAD

**Issue by jojonarte** [tarek360/Instacapture#23]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:25:9-36
  	is also present at [com.github.tarek360:instacapture:2.0.0-kotlin-beta1] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:23:5-229:19 to override.

**Comment by tarek360** [comment]
I will check it

**Comment by tarek360** [comment]
I will check it, thanks.

**Comment by jojonarte** [comment]
ok cool bro :)

**Comment by tarek360** [comment]
Hi @jojonarte 

If you didn't fix it yet, you can add the next line to the application tag in the AndroidManifest file,
```xml
tools:replace="android:allowBackup"
```
and this to override the allowBackup value, I will fix that in the next release.
