### ISSUE TITLE
activity.getWindow().getDecorView().getRootView() to SurfaceView 

### ISSUE THREAD

**Issue by sb3h** [tarek360/Instacapture#3]
The way to get a black screen

**Comment by tarek360** [comment]
InstaCapture doesn't capture SurfaceView yet.

**Comment by sb3h** [comment]
Are there any other solutions?
Can only be implemented in native?

**Comment by tarek360** [comment]
I will comment here, if I got the solution.
Thank you.

**Comment by sb3h** [comment]
OK!Thanks

**Comment by sb3h** [comment]
My requestment is because of the need to capture Unity3d.

**Comment by tarek360** [comment]
@sb3h Do you use SurfaceView or GLSurfaceView ?

**Comment by sb3h** [comment]
Yes

**Comment by tarek360** [comment]
Which one of them ?

**Comment by sb3h** [comment]
I make demo with SurfaceView is not ok.
