### ISSUE TITLE
Support Map fragment turns white when capture a screenshot again

### ISSUE THREAD

**Issue by pqtuan86** [tarek360/Instacapture#4]
I have an activity with support map fragment inside. Map is loading OK, call 
InstaCapture.getInstance(MapBaseActivity.this).capture(fileScreenShot, ignoredView, btnShareOverlay, btnShare).setScreenCapturingListener(new ScreenCaptureListener() {

```
            @Override
            public void onCaptureStarted() {
                //TODO..
                Log.d(TAG, "Capture started");
            }

            @Override
            public void onCaptureFailed(Throwable e) {
                //TODO..
                Log.d(TAG, "Capture failed");
            }

            @Override
            public void onCaptureComplete(File file) {
                //TODO..
                mScreenshotFile = file;
            }
        });
```

Everything is just fine at the first time, the screenshot contains the map and other views.
But, when i want to capture the screen again, right after the first time by calling that above method, the map was white, all other views were ok. And other tries after the 1st time were failed like that.

Any idea about this issue? Please help me to solve it.
Thanks.

**Comment by tarek360** [comment]
Hi,
Please tell me  when you call the capture() method in your activity lifecycle ?

**Comment by pqtuan86** [comment]
Hi, thanks for replying me
Basically, i trigger a button click and perform the capture() method
So, the flow is:
- Button clicked
- mMap.setOnMapLoadedCallback(onMapLoadedCallback);
- mMap.snapshot(snapshotReadyCallback);
- inside onSnapshotReady, i call capture() method

mMap here is GoogleMap instance got from onMapReady(GoogleMap)

**Comment by tarek360** [comment]
Could you upload a full sample, please?

**Comment by pqtuan86** [comment]
Could you take a look at https://github.com/pqtuan86/InstaCameraExample/blob/master/MapBaseActivity.java#L230

Thanks!

**Comment by tarek360** [comment]
Why you capture the screen in onSnapshotReady method ! 

Just put the next code in onClick your button method, also you can see our sample [here](https://github.com/tarek360/InstaCapture/blob/develop/app/src/main/java/com/tarek360/sample/BaseSampleActivity.java#L43).

``` java
InstaCapture.getInstance(MapBaseActivity.this)
          .capture(fileScreenShot, ignoredView, btnShareOverlay, btnShare)
          .setScreenCapturingListener(new SimpleScreenCapturingListener() {

            @Override public void onCaptureComplete(File file) {

              mScreenshotFile = file;
              createWAY();
            }
          });
```

Use the last code and feedback us please.

**Comment by pqtuan86** [comment]
I had done that, before i tried with the current solution, but no luck.
Note that, i shown dialog menu before really take the screen capture.

**Comment by tarek360** [comment]
Really I want to help you but I can't get the issue by these ways, please
write a new and very simple app with the issue, just the issue, without any
extra code, please make it clear and simple.
Thank you.

**Comment by pqtuan86** [comment]
Hi,
I made a simple demo for this issue, and i found another issue: 
- capture 1st time, it's ok
- i played with the map a little bit (zoom in/out, drag...), nothing is updated when i captured on 2nd time onward

Please help.
Thanks a lot.

This is the link to my demo, please check it!
https://github.com/pqtuan86/InstaCaptureWithMapDemo

**Comment by tarek360** [comment]
Hi,
I see that when you capture the screen again, it has the invisible imageView which has the last captured screen, so every time you capture the screen you will see the first screen on the top, to make sure let the imageView invisible before capturing by removing this [line](https://github.com/pqtuan86/InstaCaptureWithMapDemo/blob/master/app/src/main/java/com/example/tuanpham/demoinstacapturewithmap/MapsActivity.java#L47) from your code and make it visible after capturing in onCaptureComplete method.

best regards.

**Comment by pqtuan86** [comment]
Hi,
You're right, the problem is not that case.
I observed that, when i capture the screen, and share to SMS or social channels, the activity with Map is sent to background. And when we come back from SMS/social, and capture again, the problem is happening. Something must be wrong with the SupportMapFragment when brought back from background.
