### ISSUE TITLE
Screen not capture in Android 10 due to java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by vsay01** [tarek360/Instacapture#46]
I run the screen capture and it always, and I noticed onError trigger:

      `captureRx(activity, *ignoredViews).subscribe(object : Subscriber<Bitmap>() {
            override fun onCompleted() {}

            override fun onError(e: Throwable) {
                Logger.e(ERROR_SCREENSHOT_CAPTURE_FAILED)
                Logger.printStackTrace(e)
                screenCaptureListener.onCaptureFailed(e)
            }

            override fun onNext(bitmap: Bitmap) {
                screenCaptureListener.onCaptureComplete(bitmap)
            }
        })`

Error message: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

I run on Android 10.

**Comment by vsay01** [comment]
As a workaround I added below code to change bitmap config for android O and above:

```
val mutableBitmap = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            bitmap.copy(Bitmap.Config.RGBA_F16, true)
        } else {
            bitmap
        }
```

Then use that bitmap load to imageView, now no more error.

**Comment by tarek360** [comment]
Thank you for opening this issue!
I'm curious how does your suggested solution work when the onError method
is called?
