### ISSUE TITLE
how to capture a view ?

### ISSUE THREAD

**Issue by AllenCoder** [tarek360/Instacapture#7]
i found your lib support to capture the Acitivity Window , sometime i just want to capture a view or 
a part of layout ,how can i do it ?

**Comment by tarek360** [comment]
InstaCapture is developed to capture the full screenshot.
To convert a view to bitmap this question will help you:
http://stackoverflow.com/questions/2801116/converting-a-view-to-bitmap-without-displaying-it-in-android
