### ISSUE TITLE
How can i capture screenshot of Specific layout/view ?

### ISSUE THREAD

**Issue by Hamzabhatti6** [tarek360/Instacapture#8]
Hi,
i just want to capture the screenshot of specific RelativeLayout containing the GLSurfaceview and in other Activity it contains the GPUimage. but i haven't found any way because when it always capture the screenshot of full screen. Please guide me how can i fix my issue, Thanks

**Comment by tarek360** [comment]
You can use[ this method](https://github.com/tarek360/InstaCapture/blob/develop/instacapture/src/main/java/com/tarek360/instacapture/screenshot/ScreenshotTaker.java#L149) to capture GLSurfaceview.
