### ISSUE TITLE
InstaCapture Hangs the UI thread for a while

### ISSUE THREAD

**Issue by shishram** [tarek360/Instacapture#9]
I have a Video calling app and in that I am implementing image capturing every second, so my live stream remains still because of that. is there any way I can make image capturing stuff off the UI thread and same time I can chat seamlessly? 

Please suggest if there is other way! to achieve above mentioned task. Thanks, InstaCapture is working fine and I do appreciate your effort for making this library.

**Comment by tarek360** [comment]
Thank you for opening this issue, it's a long time when you have open this issue, You know that is the cost of capturing screenshot in the UI thread, if you get a solution, please share it, by the way, what the tool which you use to encode the screenshots to video?
